version: '2'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'password3214'
      POSTGRES_USER: 'web_user'
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_DB_HOST: 'db'
