# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a817d359af1869b9d860b140665661c7df9c0ab5f85d44aa71c396c9f52295eab6b5b7fe293473b7ae080a0d201952c0726e45f782bebefee7eea2a811f80319

test:
  secret_key_base: c3fea27cedb4ff35813d2bcab9bc3f0b779a42f60c38bf6e35cd1941fd3310303c97d70aab51d02066a241ad97f79d763e48d7846ad235659d1d31c0243b184e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
